-- ============================================================
-- FIX MISSING TABLES AND COLUMNS (V3.1 - THE COMPLETE FIX)
-- 1. Creates missing tables (mcq_attempts, practice_sessions)
-- 2. Adds ALL potential missing columns
-- 3. Sets permissions
-- ============================================================

-- 1. Ensure 'practice_sessions' table exists
CREATE TABLE IF NOT EXISTS practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES users(id),
    subtopic_id BIGINT REFERENCES subtopics(id),
    university_id BIGINT REFERENCES universities(id),
    session_type TEXT DEFAULT 'practice',
    total_questions INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    wrong_answers INTEGER DEFAULT 0,
    skipped_questions INTEGER DEFAULT 0,
    score_percentage NUMERIC DEFAULT 0,
    time_spent_seconds INTEGER DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    is_completed BOOLEAN DEFAULT FALSE
);

-- 2. Ensure 'mcq_attempts' table exists
CREATE TABLE IF NOT EXISTS mcq_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practice_session_id BIGINT REFERENCES practice_sessions(id) ON DELETE CASCADE,
    mcq_id BIGINT REFERENCES mcqs(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES users(id),
    selected_option TEXT,
    is_correct BOOLEAN DEFAULT FALSE,
    time_spent_seconds INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Ensure 'learning_streaks' table exists (Preventative)
CREATE TABLE IF NOT EXISTS learning_streaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES users(id),
    streak_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(student_id, streak_date)
);

-- 4. PATCH COLUMNS (Backup mechanism if tables existed but were missing columns)
DO $$
BEGIN
    -- practice_sessions columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'university_id') THEN
        ALTER TABLE practice_sessions ADD COLUMN university_id BIGINT REFERENCES universities(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'subtopic_id') THEN
        ALTER TABLE practice_sessions ADD COLUMN subtopic_id BIGINT REFERENCES subtopics(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'session_type') THEN
        ALTER TABLE practice_sessions ADD COLUMN session_type TEXT DEFAULT 'practice';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'correct_answers') THEN
        ALTER TABLE practice_sessions ADD COLUMN correct_answers INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'wrong_answers') THEN
        ALTER TABLE practice_sessions ADD COLUMN wrong_answers INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'skipped_questions') THEN
        ALTER TABLE practice_sessions ADD COLUMN skipped_questions INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'total_questions') THEN
        ALTER TABLE practice_sessions ADD COLUMN total_questions INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'score_percentage') THEN
        ALTER TABLE practice_sessions ADD COLUMN score_percentage NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'time_spent_seconds') THEN
         ALTER TABLE practice_sessions ADD COLUMN time_spent_seconds INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'practice_sessions' AND column_name = 'completed_at') THEN
         ALTER TABLE practice_sessions ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;
    END IF;

    -- mcq_attempts columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'mcq_attempts' AND column_name = 'time_spent_seconds') THEN
         ALTER TABLE mcq_attempts ADD COLUMN time_spent_seconds INTEGER DEFAULT 0;
    END IF;
END $$;

-- 5. Force Refresh Schema Cache
ANALYZE practice_sessions;
ANALYZE mcq_attempts;
ANALYZE learning_streaks;

-- 6. Disable RLS for development (to prevent permission errors immediately)
ALTER TABLE practice_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE mcq_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE learning_streaks DISABLE ROW LEVEL SECURITY;

-- 7. Grant Permissions
GRANT ALL ON practice_sessions TO authenticated;
GRANT ALL ON practice_sessions TO anon;
GRANT ALL ON mcq_attempts TO authenticated;
GRANT ALL ON mcq_attempts TO anon;
GRANT ALL ON learning_streaks TO authenticated;
GRANT ALL ON learning_streaks TO anon;

-- 8. Final Notice (Wrapped properly)
DO $$
BEGIN
    RAISE NOTICE '✅ Practice Schema V3.1 Applied Successfully (Tables Created/Updated)';
END $$;
